### ISSUE TITLE
Tree Problems

### ISSUE THREAD

**Issue by s-bh** [heyimShivam/Algorithm#101]
Hi @heyimShivam , can I add codes for tree traversal methods. I've seen the level order traversal has been added, so maybe I could do the pre- order traversal or post-order traversal of a binary tree?

**Comment by heyimShivam** [comment]
okay

**Comment by sajal-19** [comment]
kindly assign this to me . I want to view algorithms for tree . Like top view , bottom view, left view, right view . As these are the major problems to ask . So kindly assign this me to contribute on this.
